-- Initialize the database.
-- Drop any existing data and create empty tables.
DROP TABLE IF EXISTS SYUSER;
DROP TABLE IF EXISTS PGROUP;
DROP TABLE IF EXISTS PROJECT;
CREATE TABLE IF NOT EXISTS `SYUSER` (
  `UID` varchar(36) NOT NULL,
  `UPDATEDATETIME` datetime DEFAULT NULL,
  `CREATEDATETIME` datetime DEFAULT NULL,
  `USERNAME` varchar(100) DEFAULT NULL,
  `AVATER` varchar(200) DEFAULT NULL,
  `PASSWORD` varchar(100) DEFAULT NULL,
  -- `AGE` int(11) DEFAULT NULL,
  -- `LOGINNAME` varchar(100) NOT NULL,
  -- `SEX` varchar(1) DEFAULT NULL,
  -- `EMPLOYDATE` datetime DEFAULT NULL,
  UNIQUE KEY `UK_eiov1gsncrds3rean3dmu822p` (`USERNAME`),
  PRIMARY KEY (`UID`)
) ENGINE = InnoDB DEFAULT CHARSET = gbk;
CREATE TABLE IF NOT EXISTS `PGROUP` (
  `GID` INT(36) AUTO_INCREMENT NOT NULL,
  `ISDELETED` INT DEFAULT 0,
  `NAME` VARCHAR(100) DEFAULT NULL,
  `ICON` VARCHAR(100) DEFAULT NULL,
  `UID` varchar(36) DEFAULT NULL,
  -- KEY `USID` (`UID`),
  CONSTRAINT `FK_UID` FOREIGN KEY (`UID`) REFERENCES `SYUSER` (`UID`),
  PRIMARY KEY (`GID`)
) ENGINE = InnoDB DEFAULT CHARSET = gbk;
CREATE TABLE IF NOT EXISTS `PROJECT` (
  `PID` INT(36) AUTO_INCREMENT NOT NULL,
  `NAME` VARCHAR(100) DEFAULT NULL,
  `MODELS` VARCHAR(100) DEFAULT NULL,
  -- -- TODO
  `SETTINGTS` VARCHAR(100) DEFAULT NULL,
  -- -- TODO
  `ISDELETED` INT(36) DEFAULT 0,
  `UPDATEDATETIME` datetime DEFAULT NULL,
  `CREATEDATETIME` datetime DEFAULT NULL,
  `GID` INT(36) DEFAULT NULL,
  CONSTRAINT `FK_GID` FOREIGN KEY (`GID`) REFERENCES `PGROUP` (`GID`),
  PRIMARY key (`PID`)
) ENGINE = InnoDB DEFAULT CHARSET = gbk;